CREATE TABLE [Users] 
(
	[UserId]		UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	[FullName]		NVARCHAR(100)		NULL DEFAULT NULL,
	[Email]			NVARCHAR(256)		NOT NULL UNIQUE,
	[AvatarUrl]		NVARCHAR(2048)		NULL DEFAULT NULL
)